### ISSUE TITLE
Unity Ads SDK 4.0.1 

### ISSUE THREAD

**Issue by veyselkoparal** [artemisoftnian/com-artemisoftnian-plugins-unityads-public#3]
How can we upgrade the SDK?

Unity Ads SDK 4.0.1 and above.

**Comment by artemisoftnian** [comment]
Hi to all
I have push a new update to npm. 
https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads3
New Version:  4.2.1 

Any support is welcome on these difficult times!.
-------------------------------------------------------------------------------------------------------------------------------------------- 
If you found this Cordova Plugin useful, please consider make any donations to: 

    PayPal:   https://www.paypal.com/paypalme/WaldemarMedina
    Bitcoin:  3NawQoVTmZcVChQ3JyLqwaasBXZrWHeT3L
    Ethereum:  0xe3917C5E9B29ece099AE366dB64820A80E61702f
    BITCOIN (VIA BSC):   0xa07Fc76e9B311C111017Da1484c64b58761f7521

**Comment by veyselkoparal** [comment]
Thank you so much. You did a super job.
